baseURL = "https://Fra-Tsuna.github.io/"
languageCode = "en-us"
title = "Francesco Argenziano"
theme = "PaperMod"
staticDir = ["static"]

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  homeTitle = "Francesco Argenziano"

  # PaperMod: show posts on home
  mainSections = ["log"]

[params.homeInfoParams]
  Content = "![My portrait](/imgs/portrait.png \"My portrait\")"

[[params.homeBadges]]
  label = "Google Scholar"
  url = "https://scholar.google.com/citations?user=TCqScyQAAAAJ&hl=it"
  icon = "svg/googles-cholar-svgrepo-com.svg"
[[params.homeBadges]]
  label = "LinkedIn"
  url = "https://www.linkedin.com/in/fra-arg/"
  icon = "svg/linkedin-161-svgrepo-com.svg"
[[params.homeBadges]]
  label = "GitHub"
  url = "https://github.com/Fra-Tsuna"
  icon = "svg/github-142-svgrepo-com.svg"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
